# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Xpra
version: 0.1.0
slug: xpra
description: Xpra
url: https://github.com/felipecrs/xpra-hass-addon/tree/master/xpra
arch:
  - amd64
init: false
ingress: true
ingress_port: 8080
ingress_stream: true
panel_icon: mdi:web
video: true
map:
  - type: data
    path: /home/xpra-addon
    read_only: false
  - type: addon_config
    path: /config
    read_only: false
  - type: media
    path: /media
    read_only: false
ports:
  8080/tcp: null
